### ISSUE TITLE
Stat reports only show in console, not on the web interface

### ISSUE THREAD

**Issue by Lordanakun** [bbc/locust-load-tests#14]
Hi There,
  I really like this tool. It is quite easy to spin up.
  However, I have an issue of the statistic report. When I run a simple test on my Mac with 10 simulated users against my restful api server, everything seems fine except that the Web interface does not provide live status. In fact, the Web interface does not provide any status at all. The status report only shows up when I Ctrl+C to terminate the program in the terminal. Something like this below.
  I've searched online for a while, but couldn't find an answer how to make the Web interface alive.

Could you help? Really appreciate your time.

Anakun

[2015-08-12 12:28:00,793] /INFO/locust.main: Shutting down (exit code 0), bye.
 Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s
--------------------------------------------------------------------------------------------------------------------------------------------
 POST /research/api/v1/auth/signUp                                  5    5(50.00%)    5320     998   10135  |    6400    0.40
--------------------------------------------------------------------------------------------------------------------------------------------
 Total                                                              5   5(100.00%)                                       0.40

Percentage of the requests completed within given times
 Name                                                           # reqs    50%    66%    75%    80%    90%    95%    98%    99%   100%
--------------------------------------------------------------------------------------------------------------------------------------------
 POST /research/api/v1/auth/signUp                                   5   6400   7900   7900  10000  10000  10000  10000  10000  10135
--------------------------------------------------------------------------------------------------------------------------------------------

Error report
 # occurences       Error                                                                                               
--------------------------------------------------------------------------------------------------------------------------------------------
 5                  POST /research/api/v1/auth/signUp: '"HTTPError(\'409 Client Error: Conflict\',)"'                   
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by aidylewis** [comment]
Hi @Lordanakun 

The actual load test tool is here: https://github.com/locustio/locust
